### ISSUE TITLE
Error for element Type "button" and missing manualSwitch element

### ISSUE THREAD

**Issue by rainersc** [wolfe-labs/DU-LuaC#43]
There seems to be an error in the elementtype.ts file for the button:
```
button: {
    title: 'Button',
    value: 'pressable',
    class: 'ManualButton',
    luaClass: 'ManualButton',
    events: [
      { signature: 'onPressed()' },
      { signature: 'onReleased()' },
    ],
  },
```
if you add a button via `du-lua script-link` , the resulting .conf file will llink that entry to the pressure tile lua class.
```

button:
    name: button
    class: PressureTile
    select: null
    type:
      events: []
      methods: []
```

Additionally the element entry for a manualSwitch (ManualSwitchUnit is the class required for the conf file is missing completely in the elementtype.ts file. I tried to add it manually and recompile, but couldn't get my head around it yet....
