### ISSUE TITLE
Ability to generate control unit auto configure scripts

### ISSUE THREAD

**Issue by Snipey** [wolfe-labs/DU-LuaC#7]
The ability to use the current framework to generate the scripts to right click and apply to chair

**Comment by ghost** [comment]
That's already in there?

**Comment by Snipey** [comment]
In this format?

```
name: Gunner v2
slots:
    core:
        class: CoreUnit
    weapon:
        class: WeaponUnit
        select: manual
    radar:
        class: RadarPVPUnit
        select: manual

handlers:
    library:
        start:
            lua: |
```
